name: 🎥 Video Request
description: Request a New Video
title: "[New Video Request]: "
labels: ["new"]
assignees: "atapas"
body:
  - type: markdown
    attributes:
      value: |
        # Video Request Form
        👋 Hey There,

        You can request a video in the areas of,
        - Web Development(JavaScript, React, CSS, HTML, many more)
        - Jamstack
        - Content Creation/Blogging
        - Career
         
        ## Please provide the answer to the questions below to get started:
  - type: input
    id: new-video-name
    attributes:
      label: Suggest a Topic Name
      placeholder: "How much JavaScript is needed to learn React.js?"
    validations:
      required: true
      
  - type: textarea
    id: new-video-description
    attributes:
      label: What do you want to Learn?
      description: "Please provide some pointers."
      placeholder: |
        1. What are the important JavaScript concepts for React.js.
        2. Which array methods should master?
        3. ES6+ features like template literals, arrow function, etc.
    validations:
      required: true
      
  - type: input
    id: new-video-schedule
    attributes:
      label: How soon do you need this video tutorial?
      description: "Give minimum a couple of weeks"
      placeholder: "At your convenience."
    validations:
      required: true

  - type: textarea
    id: new-video-description
    attributes:
      label: Do you want to see your name, social handle as a requester in the Video Description?
      description: "If yes, please mention the full name, social handle, etc."
      placeholder: |
        - Tapas Adhikary
        - [twitter.com/tapasadhikary](https://twitter.com/tapasadhikary)
        - [github.com/atapas](https://github.com/atapas)
