name: 🎥 Video Request
description: Request a New Video
title: "[New Video Request]: "
labels: ["new"]
assignees: "atapas"
body:
  - type: markdown
    attributes:
      value: |
        # Video Request Form
        👋 Hey There,

        You can request a video in the areas of,
        - Web Development(JavaScript, React, CSS, HTML, many more)
        - Jamstack
        - Content Creation/Blogging
        - Career
         
        ## Please provide the answer to the questions below to get started:
  - type: input
    id: video-topic-name
    attributes:
      label: Suggest a Topic Name
      placeholder: "How much JavaScript is needed to learn React.js?"
    validations:
      required: true
      
  - type: textarea
    id: video-topic-description
    attributes:
      label: What do you want to Learn?
      description: "Please provide some pointers."
      placeholder: |
        1. What are the important JavaScript concepts for React.js
        2. Which array methods should master?
        3. ES6+ features like template literals, arrow function, etc.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
